"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_stats from './dashboard-stats.bones.json'
import _dashboard_status from './dashboard-status.bones.json'
import _dashboard_priority from './dashboard-priority.bones.json'
import _dashboard_trend from './dashboard-trend.bones.json'
import _dashboard_my_tasks from './dashboard-my-tasks.bones.json'
import _dashboard_activity from './dashboard-activity.bones.json'
import _projects_grid from './projects-grid.bones.json'
import _project_header from './project-header.bones.json'
import _kanban_board from './kanban-board.bones.json'
import _task_list from './task-list.bones.json'
import _members_list from './members-list.bones.json'
import _project_activity from './project-activity.bones.json'
import _notification_list from './notification-list.bones.json'

configureBoneyard({"color":"#e9ebf1","darkColor":"#232733","animate":"shimmer","shimmerColor":"#f4f5f8","darkShimmerColor":"#2c3140","speed":"1.6s","transition":200})

registerBones({
  "dashboard-stats": _dashboard_stats,
  "dashboard-status": _dashboard_status,
  "dashboard-priority": _dashboard_priority,
  "dashboard-trend": _dashboard_trend,
  "dashboard-my-tasks": _dashboard_my_tasks,
  "dashboard-activity": _dashboard_activity,
  "projects-grid": _projects_grid,
  "project-header": _project_header,
  "kanban-board": _kanban_board,
  "task-list": _task_list,
  "members-list": _members_list,
  "project-activity": _project_activity,
  "notification-list": _notification_list,
})
